language: android
sudo: required
dist: trusty
jdk:
    - oraclejdk8
addons:
    apt_packages:
        - lib32ncurses5
        - libstdc++6
        - lib32stdc++6
before_install:
    - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O $HOME/android-sdk.tgz
    - tar -xzf $HOME/android-sdk.tgz -C $HOME
    - export ANDROID_HOME=$HOME/android-sdk-linux
    - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
          #android:
          #    components:
          #        - tools
          #        - tools
          #        - platform-tools
          #        - build-tools-25.0.1
          #        - android-25
          #        - android-24
          #        - extra-android-m2repository
          #        - sys-img-armeabi-v7a-android-24

before_script:
    - echo y | $ANDROID_HOME/tools/android update sdk --no-ui --all --filter "tools, platform-tools"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-25"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-22"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-22;default;armeabi-v7a"
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - mksdcard -l testsdcard 1024M sdcard.img
    - emulator -avd test -sdcard sdcard.img -no-audio -no-window &
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.1"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "cmake;3.6.3155560"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "lldb;2.2"
    - echo y | $ANDROID_HOME/tools/bin/sdkmanager "ndk-bundle"
    - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
    - ./gradlew assemble lint
    - ./gradlew library:assembleDebugAndroidTest
    - ./wait-for-emulator
    - ./gradlew library:connectAndroidTest

